# Generated by Django 3.2.6 on 2021-08-13 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_person_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 8, 13, 13, 59, 48, 268167)),
        ),
    ]
