# Generated by Django 3.2.6 on 2021-08-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20210815_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='foto',
            field=models.FileField(default='/logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='social_media',
            field=models.URLField(default='https://www.djangoproject.com/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
