# Generated by Django 3.2.6 on 2021-08-16 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_rename_foto_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
