# Generated by Django 3.2.6 on 2021-08-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_alter_person_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
